### PR TITLE
Fixed compile errors with GCC 4.8

### PR DESCRIPTION
**Pull request by bjorn**
Also fixed some warnings from header files that were being particularly spammy to the compile output.

Just asking you to accept these so that I won't have to fix them again next time I check out "TileZed". :-)

Ever planning to open some more pull requests to Tiled, btw? You've done an amazing amount of work which makes it a bit hard for me to know whether there's anything of interest to general Tiled users out there. Except I can just check it out and see if there's any features I like. But, I guess we've been diverging quite a bit now making such things ever harder.

### CODE REVIEW

**Comment by timbaker** [comment]
Thanks, I 'll look at this when I get a moment.  You're right, merging would be difficult now.  :-)

**Comment by timbaker** [comment]
I fixed almost all the warnings etc GCC 4.7 gave me.

**Comment by bjorn** [comment]
Erm, this was not a bug report, but a pull request. Was something wrong with my fixes?

**Comment by timbaker** [comment]
Nothing was wrong with them.  I just felt more comfortable fixing everything on my computer rather than merging on github (bit of a newb thing on my part).  Is there something I should do to clean up this pull request?

**Comment by bjorn** [comment]
Nothing left to do, no. I just feel a bit bad since you ignored my work. You don't have to merge on github, you could have also applied my patch manually if you prefer that.

Anyway, I'm sure things will compile for me cleanly now, so thanks for fixing everything up!

**Pull request closed without merging**
